### ISSUE TITLE
more packages?

### ISSUE THREAD

**Issue by johnynek** [non/algebra#105] opened 2015-10-29 20:57 UTC
we could break core into algebra-core, algebra-ring (depends on core), algebra-lattice (depends on ring).

It might be easier to maintain binary stability in a smaller algebra-core which has fewer concepts, which are incidentally the ones most commonly used in Cats, Algebird, Scalding and Summingbird.

**Comment by avibryant** [comment] 2015-10-29 21:02
I'd be in favor of this change.

**Comment by rklaehn** [comment] 2015-10-29 21:04
Isn't this a duplicate of #43? In any case, I would be in favour.

**Comment by non** [comment] 2015-10-29 21:23
Makes sense to me. Let's do it!

**Comment by johnynek** [comment] 2015-10-29 21:24
@rklaehn yep. Sorry. My bad. +1 to @non 's original idea.

**Closed** 2015-11-21 16:47 UTC
